### ISSUE TITLE
zuul/src/main/java/com/lovnx/filter/ResultFilter.java:[6,47] package io.reactivex.netty.protocol.http.server does not exist

### ISSUE THREAD

**Issue by ighack** [Lovnx/micro-service#3]
zuul/src/main/java/com/lovnx/filter/ResultFilter.java:[6,47] package io.reactivex.netty.protocol.http.server does not exist

**Comment by Tyran820** [comment]
I also encountered this problem. Do you have a solution?

**Comment by ighack** [comment]
java -jar xxx.jar -Djava.io.tmpdir=/tmp

/tmp can be any dir
